TASK_LIST = "Список задач"
ADD_TASK = "Добавить задачу"

EDIT_TASK_STATUS = "Изменить статус задачи/просмотр"
DELETE_TASKS_BY_DATE = "Удалить задачи на конкретную дату"
YES = "Да"
NO = "Нет"
BACK = "←"
FORWARD = "→"
RETURN = "Вернуться↩️"

COMPLETE = "Выполнено"
DELETE = "Удалить"
PROLONG = "Продлить"
EDIT_TEXT = "Изменить текст"
